<template>
    <div class="dinner-wrapper">
        <!--ページトップ部分-->
        <dinnerdetail :header="header" :datas="datas"></dinnerdetail>
        <!--ページのメインの部分-->
        <dinnermenu :datas="dinnermenu"></dinnermenu>
    </div>
</template>
<script>
import dinnerdetail from '@/components/Parts/dinnerdetail.vue'
import dinnermenu from '@/components/Parts/DinnerMenu.vue'
export default {
    components:{
        dinnerdetail,
        dinnermenu,
    },
    data:function(){
        return{
            header:{
                title:'会席料理について',
                img:require('@/assets/images/fukumatu_food_title.png'),
            },
            datas:[
                {
                    title:'見て楽しんで、香りを楽しんで、味を楽しむ',
                    text:'店主は日比谷・赤坂の料亭で厳しい修行を積んだ板前。直接市場へ出向いて、厳選した食材を仕入れて一から吟味して調理しております。タイトルにあります様に、お客様に五感で料理を楽しんでいただけるよう、どの料理をとっても店主の手作りにこだわり、とにかく美食を追求しております。',
                    subtitle:'ご相談について',
                    subtext:'福松家ではそれぞれのお客様の要望に沿えるよう、できうる限りのご相談に乗ります。まずはお電話から、お気軽にご相談ください。',
                    subexamples:[
                        {
                            title:'生物が食べられないお客様 ',
                            text:'→代わりに焼き魚や煮物、火を通した料理を提供いたしました。'
                        },
                        {
                            title:'病気で食事が制限されている',
                            text:'→塩分を抜いた料理を提供いたしました。玉子焼きでは出汁を抜き、焼き鳥はタレをつけず焼くなどを致しました。'
                        }
                    ],
                    imgtitle:'太平山名物・だんご'
                }
            ],
            dinnermenu:[
                {
                    title:'季節コース',
                    text:'季節の食材を使った会席料理。コース値段によって中身の食材がかわります。',
                    img:require('@/assets/images/enkai-basic.jpg'),
                    alt:"季節コース",
                    menu:[
                        {
                            price:'3000円',
                            detail:'こちらはメニューの一覧ですこちらはメニューの一覧ですこちらはメニューの一覧ですこちらはメニューの一覧です',
                        },
                        {
                            price:'3500円',
                            detail:'こちらはメニューの一覧ですこちらはメニューの一覧ですこちらはメニューの一覧ですこちらはメニューの一覧ですこちらはメニューの一覧ですこちらはメニューの一覧です',
                        },
                        {
                            price:'4000円',
                            detail:'こちらはメニューの一覧ですこちらはメニューの一覧ですこちらはメニューの一覧ですこちらはメニューの一覧ですこちらはメニューの一覧ですこちらはメニューの一覧です',
                        },
                        {
                            price:'5000円',
                            detail:'こちらはメニューの一覧ですこちらはメニューの一覧ですこちらはメニューの一覧ですこちらはメニューの一覧ですこちらはメニューの一覧ですこちらはメニューの一覧ですこちらはメニューの一覧ですこちらはメニューの一覧です',
                        }
                    ]
                },
                {
                    title:'お任せコース',
                    text:'とにかく旨いものが食べたいというグルメ好きにおすすめです。食材にこだわりをもって旬の会席料理をお出し致します。',
                    img:require('@/assets/images/enkai-basic2.jpg'),
                    alt:"お任せコース",
                    menu:[
                        {
                            price:'5000〜8000円',
                            detail:'こちらはメニューの一覧ですこちらはメニューの一覧ですこちらはメニューの一覧ですこちらはメニューの一覧ですこちらはメニューの一覧ですこちらはメニューの一覧です',
                        }
                    ]
                },
                {
                    title:'ふぐコース',
                    text:'ふぐコースは期間限定で下関のとらふぐをうすづくり、からあげ、鍋などふぐづくしのフルコースです。',
                    img:require('@/assets/images/fugu.jpg'),
                    alt:"ふぐコース",
                    menu:[
                        {
                            price:'7000〜8000円',
                            detail:'こちらはメニューの一覧ですこちらはメニューの一覧ですこちらはメニューの一覧ですこちらはメニューの一覧ですこちらはメニューの一覧ですこちらはメニューの一覧です',
                        }
                    ]
                },
/*                 {
                    title:'伊勢コース',
                    text:'活けの伊勢海老を使ったコースです。',
                    alt:"伊勢コース",
                    menu:[
                        {
                            price:'時価',
                            detail:'こちらはメニューの一覧ですこちらはメニューの一覧ですこちらはメニューの一覧ですこちらはメニューの一覧ですこちらはメニューの一覧ですこちらはメニューの一覧です',
                        }
                    ]
                } */
            ]
        }
    }
}
</script>
<style scoped lang="scss">
.dinner-wrapper{
    overflow:hidden;
    width:100vw;
}
</style>